name: codebook-app-env
# Conda environment for the bilingual (English/French) Codebook Generator Shiny app
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3
  - r-shiny
  - r-shinyjs
  - r-shinythemes
  - r-shinybs
  - r-rhandsontable
  - r-readxl
  - r-dt
  - r-devtools
  - r-tidyverse
